package com.openclassrooms.paymybuddy.model;

import lombok.*;

import javax.persistence.*;
import javax.validation.constraints.Max;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotNull;
import java.time.LocalDateTime;

/**
 * Class that manage the entity transaction
 *
 * @author Christine Duarte
 */
@Entity
@Getter
@Setter
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class Transaction {
    /**
     * Attribute which containing an Integer with the transaction id it's
     * the primary key of the table transaction
     * id autogenerated
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "transaction_id")
    private Integer transactionId;

    /**
     * A Double with the amount of transaction
     * the value cannot  be null, and it must be between 1 and 1000
     */
      private Double amount;

    /**
     * A String with the description of the transaction
     */
    private String description;

    /**
     * A Double with the fees of the transaction
     */
    private Double fees;

    /**
     * A LocaldateTime which containing dote of transaction
     */
    private LocalDateTime date;

    /**
     * An Instance of User emitter that permit joint the table transaction with the table user
     * in the column emitter_email
     * relationship type of many to one
     */
    @ManyToOne(cascade = CascadeType.ALL, fetch = FetchType.EAGER)
    @JoinColumn(name = "emitter_email")
    private User userEmitter;

    /**
     * An Instance of User receiver that permit joint the table transaction with the table user
     * in the column receiver_email
     * relationship type of many to one
     */
    @ManyToOne(cascade = CascadeType.ALL, fetch = FetchType.EAGER)
    @JoinColumn(name = "receiver_email")
    private User userReceiver;

    @Override
    public String toString() {
        return "Transaction{" +
                "transactionId=" + transactionId +
                ", amount=" + amount +
                ", description='" + description + '\'' +
                ", fees=" + fees +
                ", date=" + date +
                ", userEmitter=" + userEmitter +
                ", userReceiver=" + userReceiver +
                '}';
    }
}
