package com.openclassrooms.paymybuddy.model;

import lombok.*;

import javax.persistence.*;
import java.time.LocalDateTime;
/**
 * Class that manage the entity transfer
 * A user can Credit his account
 * in application
 * and transfer money to his account bank
 *
 * @author Christine Duarte
 */
@Entity
@Setter
@Getter
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class Transfer {
    /**
     * Attribute which containing an Integer with the transfer id it's
     * the primary key of the table transfer
     * id autogenerated
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "transfer_id")
    private Integer transferId;

    /**
     * A LocalDateTime which containing dote of transfer
     */
    private LocalDateTime date;

    /**
     * An enumeration with values CREDIT, DEBIT for choose the type of transfer
     */
    @Enumerated(value = EnumType.STRING)
    @Column(name = "transfer_type")
    private TransferTypeEnum transferType;

    /**
     * A Double with the amount of transfer
     */
    private Double amount;

    /**
     * A String with the description of the transfer
     */
    private String description;

    /**
     * A Double with the value of the balance of the user after the transfer
     */
    @Column(name = "post_trade_balance")
    private Double postTradeBalance;

    /**
     * An Instance of User
     * this attribute determines the relationship many to one with the table user
     * and permit join the table transfer to the table user in the user_email column
     */
    @ManyToOne(cascade = CascadeType.ALL, fetch = FetchType.EAGER)
    @JoinColumn(name = "user_email")
    private User user;

    /**
     * Method toString
     *
     * @return a String of the object Transfer
     */
    @Override
    public String toString() {
        return "Transfer{" +
                "transferId=" + transferId +
                ", date=" + date +
                ", transferType=" + transferType +
                ", amount=" + amount +
                ", description='" + description + '\'' +
                ", postTradeBalance=" + postTradeBalance +
                ", user=" + user +
                '}';
    }
}
